### ISSUE TITLE
Zone 3 mispositioned

### ISSUE THREAD

**Issue by zedin27** [AlexEzzeddine/campus42#1]
When some of the users are logged in the very back of zone 3 (near to bocal/gaetan door), the computer user is **swap with a different computer**. I can show you an example whenever.

**Comment by AlexEzzeddine** [comment]
I’m going to check this tonight. Thank you for opening the issue! I will let you know when I fix it 😀

**Comment by AlexEzzeddine** [comment]
So I  have fixed the problem. 3 rows were wrong because I thought that bocal used the same pattern for all of the rows in this zone but apparently this pattern does not apply for rows 7, 8 and 9.
Thanks again for opening an issue, Zeid, I am happy to close it. First issue ever solved! 😄
